# Generated by Django 4.2.10 on 2024-04-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='remember_token',
        ),
    ]
