# Generated by Django 4.2.10 on 2024-06-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_user_remember_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_genres',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_movies',
            field=models.JSONField(default=list),
        ),
    ]
